using System.Linq;
using System.Text;
using ZeroAlloc.ValueObjects.Generator.Models;

namespace ZeroAlloc.ValueObjects.Generator.Writers;

internal static class SourceWriter
{
    private static readonly System.Collections.Generic.HashSet<string> s_formattable = new(System.StringComparer.Ordinal)
    {
        // Keyword form (default Roslyn ToDisplayString for primitives).
        "int", "long", "short", "byte", "uint", "ulong", "ushort", "sbyte",
        "float", "double", "decimal",
        // FQN form (defensive — covers non-keyword BCL formattables and any future format change).
        "System.Int32", "System.Int64", "System.Int16", "System.Byte",
        "System.UInt32", "System.UInt64", "System.UInt16", "System.SByte",
        "System.Single", "System.Double", "System.Decimal",
        "System.DateTime", "System.DateTimeOffset",
        "System.DateOnly", "System.TimeOnly", "System.TimeSpan",
        "System.Guid", "System.Numerics.BigInteger",
    };

    private static bool IsFormattable(string typeName) => s_formattable.Contains(typeName);

    private static bool IsStringType(string typeName)
        => string.Equals(typeName, "string", System.StringComparison.Ordinal)
           || string.Equals(typeName, "System.String", System.StringComparison.Ordinal);

    private static bool IsValueType(string typeName)
        => IsFormattable(typeName)
           || string.Equals(typeName, "bool", System.StringComparison.Ordinal)
           || string.Equals(typeName, "char", System.StringComparison.Ordinal)
           || string.Equals(typeName, "System.Boolean", System.StringComparison.Ordinal)
           || string.Equals(typeName, "System.Char", System.StringComparison.Ordinal);

    private static string ChooseToStringExpr(EqualityProperty p)
    {
        if (IsStringType(p.TypeName))
            return p.IsNullable ? $"{p.Name} ?? \"\"" : p.Name;

        if (IsFormattable(p.TypeName))
            return p.IsNullable
                ? $"{p.Name}?.ToString(global::System.Globalization.CultureInfo.InvariantCulture) ?? \"\""
                : $"{p.Name}.ToString(global::System.Globalization.CultureInfo.InvariantCulture)";

        return p.IsNullable
            ? $"{p.Name}?.ToString() ?? \"\""
            : $"{p.Name}.ToString()";
    }

    public static string Write(ValueObjectModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        // The <auto-generated> header suppresses analyzer diagnostics but not compiler ones,
        // so CS1591 still fires on every public member for consumers who enable
        // GenerateDocumentationFile. Suppress it here — file-scoped, so it can't leak into
        // the consumer's hand-written code.
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        string typeKind = model.IsStruct ? "readonly partial struct" : "sealed partial class";
        sb.AppendLine($"{typeKind} {model.TypeName} : System.IEquatable<{model.TypeName}>");
        sb.AppendLine("{");

        WriteEquals(sb, model);
        WriteIEquatable(sb, model);
        WriteGetHashCode(sb, model);
        WriteOperators(sb, model);
        WriteToString(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void WriteEquals(StringBuilder sb, ValueObjectModel model)
    {
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine($"    public override bool Equals(object? obj) =>");
        sb.AppendLine($"        obj is {model.TypeName} other && Equals(other);");
        sb.AppendLine();
    }

    private static void WriteIEquatable(StringBuilder sb, ValueObjectModel model)
    {
        // Structs can't be null; classes use T? to satisfy IEquatable<T> contract in nullable context
        string paramType = model.IsStruct ? model.TypeName : $"{model.TypeName}?";

        sb.AppendLine("    /// <inheritdoc/>");

        if (model.Properties.Count == 0)
        {
            sb.AppendLine($"    public bool Equals({paramType} other) =>");
            sb.AppendLine(model.IsStruct ? "        true;" : "        other is not null;");
        }
        else
        {
            sb.AppendLine($"    public bool Equals({paramType} other) =>");

            var comparisons = model.Properties.Select(p =>
                p.IsNullable
                    ? $"(other.{p.Name} is null ? {p.Name} is null : {p.Name} == other.{p.Name})"
                    : $"{p.Name} == other.{p.Name}");

            // For classes, guard against null before accessing members
            if (!model.IsStruct)
            {
                sb.AppendLine("        other is not null &&");
            }

            sb.AppendLine("        " + string.Join(" &&\n        ", comparisons) + ";");
        }
        sb.AppendLine();
    }

    private static void WriteGetHashCode(StringBuilder sb, ValueObjectModel model)
    {
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine("    public override int GetHashCode()");
        sb.AppendLine("    {");

        if (model.Properties.Count == 0)
        {
            sb.AppendLine("        return 0;");
        }
        else if (model.Properties.Count == 1)
        {
            var p = model.Properties[0];
            // For known value types (incl. Nullable<T>), .GetHashCode() is null-safe by construction.
            // For reference types, the value can be null at runtime even when not nullable-annotated —
            // use the null-conditional form unconditionally for safety. The JIT inlines this away
            // for the non-null fast path.
            var expr = IsValueType(p.TypeName)
                ? $"{p.Name}.GetHashCode()"
                : $"{p.Name}?.GetHashCode() ?? 0";
            sb.AppendLine($"        return {expr};");
        }
        else if (model.Properties.Count <= 8)
        {
            var args = string.Join(", ", model.Properties.Select(p => p.Name));
            sb.AppendLine($"        return System.HashCode.Combine({args});");
        }
        else
        {
            sb.AppendLine("        var hc = new System.HashCode();");
            foreach (var p in model.Properties)
                sb.AppendLine($"        hc.Add({p.Name});");
            sb.AppendLine("        return hc.ToHashCode();");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void WriteOperators(StringBuilder sb, ValueObjectModel model)
    {
        // Operators are new members — they inherit no documentation, so they get real summaries.
        if (model.IsStruct)
        {
            // Structs can't be null — simple delegation is safe
            WriteOperatorDoc(sb, model.TypeName, equality: true);
            sb.AppendLine($"    public static bool operator ==({model.TypeName} left, {model.TypeName} right) => left.Equals(right);");
            WriteOperatorDoc(sb, model.TypeName, equality: false);
            sb.AppendLine($"    public static bool operator !=({model.TypeName} left, {model.TypeName} right) => !left.Equals(right);");
        }
        else
        {
            // Classes: left may be null — use null-safe pattern
            WriteOperatorDoc(sb, model.TypeName, equality: true);
            sb.AppendLine($"    public static bool operator ==({model.TypeName}? left, {model.TypeName}? right) => left is null ? right is null : left.Equals(right);");
            WriteOperatorDoc(sb, model.TypeName, equality: false);
            sb.AppendLine($"    public static bool operator !=({model.TypeName}? left, {model.TypeName}? right) => !(left == right);");
        }
        sb.AppendLine();
    }

    private static void WriteOperatorDoc(StringBuilder sb, string typeName, bool equality)
    {
        var verb = equality ? "equal" : "not equal";
        // No <see cref="..."/> to generated or consumer symbols: an unresolved cref raises
        // CS1574, which under TreatWarningsAsErrors would recreate the very class of consumer
        // build break this documentation exists to avoid. <c> is inert. (crefs to BCL types are
        // safe — corelib is always referenced — and are used for <exception> in the TypedId
        // writers. GeneratedCodeDocumentationTests asserts no doc diagnostics of any kind.)
        sb.AppendLine($"    /// <summary>Determines whether two <c>{typeName}</c> values are {verb} by comparing their equality members.</summary>");
        sb.AppendLine("    /// <param name=\"left\">The left operand.</param>");
        sb.AppendLine("    /// <param name=\"right\">The right operand.</param>");
        sb.AppendLine($"    /// <returns><see langword=\"true\"/> if the values are {verb}; otherwise <see langword=\"false\"/>.</returns>");
    }

    private static void WriteToString(StringBuilder sb, ValueObjectModel model)
    {
        // ToString overrides Object.ToString, but the generated format is specific enough
        // to be worth stating rather than inheriting Object's generic description.
        if (model.Properties.Count == 0)
        {
            sb.AppendLine($"    /// <summary>Returns the constant string \"{model.TypeName} {{ }}\", as this type has no equality members.</summary>");
            sb.AppendLine($"    public override string ToString() => \"{model.TypeName} {{ }}\";");
            return;
        }

        if (model.Properties.Count == 1)
        {
            var expr = ChooseToStringExpr(model.Properties[0]);
            sb.AppendLine($"    /// <summary>Returns the string form of <c>{model.Properties[0].Name}</c>, without wrapping type or property names.</summary>");
            sb.AppendLine($"    public override string ToString() => {expr};");
            return;
        }

        sb.AppendLine($"    /// <summary>Returns a string listing each equality member of this <c>{model.TypeName}</c> as Name = value.</summary>");
        var parts = string.Join(", ", model.Properties.Select(p => p.Name + " = {" + p.Name + "}"));
        sb.AppendLine("    public override string ToString() => $\"" + model.TypeName + " {{ " + parts + " }}\";");
    }
}
