using ZeroAlloc.ValueObjects.Generator.Models;

namespace ZeroAlloc.ValueObjects.Generator.Writers;

internal static class TypedIdStubWriter
{
    public static string Write(TypedIdModel model)
    {
        var strategyName = model.Strategy switch
        {
            0 => "Ulid",
            1 => "Uuid7",
            2 => "Snowflake",
            3 => "Sequential",
            _ => "Unknown",
        };
        var backingName = model.Backing switch
        {
            1 => "Guid",
            2 => "Int64",
            _ => "Unknown",
        };

        var nsLine = model.Namespace is null ? string.Empty : $"namespace {model.Namespace};\n\n";
        return $"""
            // <auto-generated/>
            // TODO: TypedId writer pending (Tasks 9+10)

            {nsLine}#pragma warning disable CS8019 // unused usings are acceptable in stubs
            // Strategy: {strategyName}, Backing: {backingName}
            // Partial struct will be filled in by the writer.
            """;
    }
}
