using System;
using System.Text;
using ZeroAlloc.ValueObjects.Generator.Models;

namespace ZeroAlloc.ValueObjects.Generator.Writers;

internal static class TypedIdGuidWriter
{
    public static string Write(TypedIdModel model)
    {
        var sb = new StringBuilder();
        AppendHeader(sb, model);
        AppendTypeDeclaration(sb, model.Name);
        AppendValueAndCtor(sb, model.Name);
        AppendFactoryAndFormatting(sb, model.Name, model.Strategy);
        AppendParsing(sb, model.Name, model.Strategy);
        AppendComparable(sb, model.Name);
        AppendJsonConverter(sb, model.Name);
        AppendZeroAllocSerializer(sb, model.Name);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb, TypedIdModel model)
    {
        sb.AppendLine("// <auto-generated/>");
        // The <auto-generated> header suppresses analyzer diagnostics but not compiler ones,
        // so CS1591 still fires on every public member for consumers who enable
        // GenerateDocumentationFile. Suppress it here — file-scoped, so it can't leak into
        // the consumer's hand-written code.
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using ZeroAlloc.ValueObjects;");
        sb.AppendLine();
        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }
    }

    private static void AppendTypeDeclaration(StringBuilder sb, string name)
    {
        sb.AppendLine($"[JsonConverter(typeof({name}.TypedIdJsonConverter))]");
        sb.AppendLine($"public readonly partial record struct {name} :");
        sb.AppendLine($"    IEquatable<{name}>,");
        sb.AppendLine($"    IComparable<{name}>,");
        sb.AppendLine($"    IParsable<{name}>,");
        sb.AppendLine($"    ISpanParsable<{name}>");
        sb.AppendLine("{");
    }

    private static void AppendValueAndCtor(StringBuilder sb, string name)
    {
        sb.AppendLine("    /// <summary>The underlying GUID this identifier wraps.</summary>");
        sb.AppendLine("    public Guid Value { get; }");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Wraps an existing GUID as a <c>{name}</c>. No validation is performed.</summary>");
        sb.AppendLine("    /// <param name=\"value\">The GUID to wrap.</param>");
        sb.AppendLine($"    public {name}(Guid value) => Value = value;");
        sb.AppendLine();
    }

    private static void AppendFactoryAndFormatting(StringBuilder sb, string name, int strategy)
    {
        var newCall = strategy switch
        {
            0 => "UlidCore.NewGuid()",
            1 => "Uuid7Core.NewGuid()",
            _ => throw new InvalidOperationException($"Unexpected Guid-backed strategy {strategy}"),
        };
        // For UUIDv7 we emit Guid.ToString("D", InvariantCulture). UUIDv7 structs store the
        // 128 bits in big-endian order via GuidBigEndianHelpers at construction time, so
        // Guid.ToString("D") — despite .NET's mixed-endian Data1/Data2/Data3 quirk —
        // produces the canonical hyphenated form that reflects the RFC 9562 byte layout.
        var toStringCall = strategy switch
        {
            0 => "UlidCore.ToBase32(Value)",
            1 => "Value.ToString(\"D\", CultureInfo.InvariantCulture)",
            _ => throw new InvalidOperationException($"Unexpected Guid-backed strategy {strategy}"),
        };

        var newDoc = strategy switch
        {
            0 => "Creates a new identifier backed by a ULID: time-ordered and lexicographically sortable by its string form.",
            1 => "Creates a new identifier backed by a UUIDv7 (RFC 9562): time-ordered and sortable by its byte layout.",
            _ => throw new InvalidOperationException($"Unexpected Guid-backed strategy {strategy}"),
        };
        var toStringDoc = strategy switch
        {
            0 => "Returns the 26-character Crockford base32 ULID form. This is the form accepted by Parse and TryParse.",
            1 => "Returns the canonical hyphenated GUID form. This is the form accepted by Parse and TryParse.",
            _ => throw new InvalidOperationException($"Unexpected Guid-backed strategy {strategy}"),
        };

        sb.AppendLine($"    /// <summary>{newDoc}</summary>");
        sb.AppendLine("    /// <returns>A new unique identifier.</returns>");
        sb.AppendLine($"    public static {name} New() => new({newCall});");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>{toStringDoc}</summary>");
        sb.AppendLine($"    public override string ToString() => {toStringCall};");
        sb.AppendLine();
    }

    private static void AppendParsing(StringBuilder sb, string name, int strategy)
    {
        // Ulid: strict 26-char Crockford base32. Uuid7: accept any standard Guid format.
        var tryParseExpr = strategy switch
        {
            0 => "UlidCore.TryFromBase32(s, out var parsed)",
            1 => "Guid.TryParse(s, out var parsed)",
            _ => throw new InvalidOperationException($"Unexpected Guid-backed strategy {strategy}"),
        };

        TypedIdDocs.AppendParseDoc(sb, name, span: false, nullThrows: true);
        sb.AppendLine($"    public static {name} Parse(string s, IFormatProvider? provider = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (s is null) throw new ArgumentNullException(nameof(s));");
        sb.AppendLine("        if (TryParse(s.AsSpan(), provider, out var r)) return r;");
        sb.AppendLine($"        throw new FormatException($\"Value is not a valid {name}.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        TypedIdDocs.AppendTryParseDoc(sb, name, span: false);
        sb.AppendLine($"    public static bool TryParse(string? s, IFormatProvider? provider, out {name} result)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (s is null) { result = default; return false; }");
        sb.AppendLine("        return TryParse(s.AsSpan(), provider, out result);");
        sb.AppendLine("    }");
        sb.AppendLine();
        TypedIdDocs.AppendParseDoc(sb, name, span: true, nullThrows: false);
        sb.AppendLine($"    public static {name} Parse(ReadOnlySpan<char> s, IFormatProvider? provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (TryParse(s, provider, out var r)) return r;");
        sb.AppendLine($"        throw new FormatException($\"Value is not a valid {name}.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        TypedIdDocs.AppendTryParseDoc(sb, name, span: true);
        sb.AppendLine($"    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out {name} result)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if ({tryParseExpr})");
        sb.AppendLine("        {");
        sb.AppendLine($"            result = new {name}(parsed);");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        result = default;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendComparable(StringBuilder sb, string name)
    {
        TypedIdDocs.AppendCompareToDoc(sb, name);
        sb.AppendLine($"    public int CompareTo({name} other) => Value.CompareTo(other.Value);");
        sb.AppendLine();
        // MA0097 requires comparison operators on types that implement IComparable<T>.
        TypedIdDocs.AppendComparisonOperatorDoc(sb, name, "less than");
        sb.AppendLine($"    public static bool operator <({name} left, {name} right) => left.CompareTo(right) < 0;");
        TypedIdDocs.AppendComparisonOperatorDoc(sb, name, "greater than");
        sb.AppendLine($"    public static bool operator >({name} left, {name} right) => left.CompareTo(right) > 0;");
        TypedIdDocs.AppendComparisonOperatorDoc(sb, name, "less than or equal to");
        sb.AppendLine($"    public static bool operator <=({name} left, {name} right) => left.CompareTo(right) <= 0;");
        TypedIdDocs.AppendComparisonOperatorDoc(sb, name, "greater than or equal to");
        sb.AppendLine($"    public static bool operator >=({name} left, {name} right) => left.CompareTo(right) >= 0;");
        sb.AppendLine();
    }

    private static void AppendJsonConverter(StringBuilder sb, string name)
    {
        TypedIdDocs.AppendJsonConverterDoc(sb, name);
        sb.AppendLine($"    public sealed class TypedIdJsonConverter : JsonConverter<{name}>");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine($"        public override {name} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            var s = reader.GetString();");
        sb.AppendLine("            return s is not null && TryParse(s, CultureInfo.InvariantCulture, out var id)");
        sb.AppendLine("                ? id");
        sb.AppendLine($"                : throw new JsonException($\"Invalid {name} value.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine($"        public override void Write(Utf8JsonWriter writer, {name} value, JsonSerializerOptions options)");
        sb.AppendLine("            => writer.WriteStringValue(value.ToString());");
        sb.AppendLine("    }");
    }

    // Emits a nested ISerializer<TypedId> implementation alongside the existing
    // JsonConverter<T>. Closes ValueObjects#25 — additive integration with
    // ZeroAlloc.Serialisation. Guarded by the modern-TFM symbol because the
    // package reference to ZeroAlloc.Serialisation is conditional on the same
    // TFM in ZeroAlloc.ValueObjects.csproj. The byte form is the canonical
    // 16-byte big-endian Guid representation (RFC 9562 layout) — zero-alloc
    // round-trip via Guid.TryWriteBytes / new Guid(ReadOnlySpan<byte>).
    private static void AppendZeroAllocSerializer(StringBuilder sb, string name)
    {
        sb.AppendLine();
        sb.AppendLine("#if NETSTANDARD2_1_OR_GREATER || NET");
        sb.AppendLine($"    internal sealed class TypedIdSerializer : global::ZeroAlloc.Serialisation.ISerializer<{name}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public void Serialize(global::System.Buffers.IBufferWriter<byte> writer, {name} value)");
        sb.AppendLine("        {");
        sb.AppendLine("            var span = writer.GetSpan(16);");
        sb.AppendLine("            if (!value.Value.TryWriteBytes(span))");
        sb.AppendLine($"                throw new global::System.InvalidOperationException(\"Failed to write Guid bytes for {name}.\");");
        sb.AppendLine("            writer.Advance(16);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {name} Deserialize(global::System.ReadOnlySpan<byte> buffer)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (buffer.Length < 16)");
        sb.AppendLine($"                throw new global::System.ArgumentException($\"Buffer too small to deserialize {name}; need 16 bytes, got {{buffer.Length}}.\", nameof(buffer));");
        sb.AppendLine($"            return new {name}(new global::System.Guid(buffer.Slice(0, 16)));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("#endif");
    }
}
