using System;
using System.Text;
using ZeroAlloc.ValueObjects.Generator.Models;

namespace ZeroAlloc.ValueObjects.Generator.Writers;

internal static class TypedIdGuidWriter
{
    public static string Write(TypedIdModel model)
    {
        var sb = new StringBuilder();
        AppendHeader(sb, model);
        AppendTypeDeclaration(sb, model.Name);
        AppendValueAndCtor(sb, model.Name);
        AppendFactoryAndFormatting(sb, model.Name, model.Strategy);
        AppendParsing(sb, model.Name, model.Strategy);
        AppendComparable(sb, model.Name);
        AppendJsonConverter(sb, model.Name);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb, TypedIdModel model)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using ZeroAlloc.ValueObjects;");
        sb.AppendLine();
        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }
    }

    private static void AppendTypeDeclaration(StringBuilder sb, string name)
    {
        sb.AppendLine($"[JsonConverter(typeof({name}.TypedIdJsonConverter))]");
        sb.AppendLine($"public readonly partial record struct {name} :");
        sb.AppendLine($"    IEquatable<{name}>,");
        sb.AppendLine($"    IComparable<{name}>,");
        sb.AppendLine($"    IParsable<{name}>,");
        sb.AppendLine($"    ISpanParsable<{name}>");
        sb.AppendLine("{");
    }

    private static void AppendValueAndCtor(StringBuilder sb, string name)
    {
        sb.AppendLine("    public Guid Value { get; }");
        sb.AppendLine();
        sb.AppendLine($"    public {name}(Guid value) => Value = value;");
        sb.AppendLine();
    }

    private static void AppendFactoryAndFormatting(StringBuilder sb, string name, int strategy)
    {
        var newCall = strategy switch
        {
            0 => "UlidCore.NewGuid()",
            1 => "Uuid7Core.NewGuid()",
            _ => throw new InvalidOperationException($"Unexpected Guid-backed strategy {strategy}"),
        };
        var toStringCall = strategy switch
        {
            0 => "UlidCore.ToBase32(Value)",
            1 => "Value.ToString(\"D\", CultureInfo.InvariantCulture)",
            _ => throw new InvalidOperationException($"Unexpected Guid-backed strategy {strategy}"),
        };

        sb.AppendLine($"    public static {name} New() => new({newCall});");
        sb.AppendLine();
        sb.AppendLine($"    public override string ToString() => {toStringCall};");
        sb.AppendLine();
    }

    private static void AppendParsing(StringBuilder sb, string name, int strategy)
    {
        // Ulid: strict 26-char Crockford base32. Uuid7: accept any standard Guid format.
        var tryParseExpr = strategy switch
        {
            0 => "UlidCore.TryFromBase32(s, out var parsed)",
            1 => "Guid.TryParse(s, out var parsed)",
            _ => throw new InvalidOperationException($"Unexpected Guid-backed strategy {strategy}"),
        };

        sb.AppendLine($"    public static {name} Parse(string s, IFormatProvider? provider = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (s is null) throw new ArgumentNullException(nameof(s));");
        sb.AppendLine("        if (TryParse(s.AsSpan(), provider, out var r)) return r;");
        sb.AppendLine($"        throw new FormatException($\"Value is not a valid {name}.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static bool TryParse(string? s, IFormatProvider? provider, out {name} result)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (s is null) { result = default; return false; }");
        sb.AppendLine("        return TryParse(s.AsSpan(), provider, out result);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {name} Parse(ReadOnlySpan<char> s, IFormatProvider? provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (TryParse(s, provider, out var r)) return r;");
        sb.AppendLine($"        throw new FormatException($\"Value is not a valid {name}.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out {name} result)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if ({tryParseExpr})");
        sb.AppendLine("        {");
        sb.AppendLine($"            result = new {name}(parsed);");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        result = default;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendComparable(StringBuilder sb, string name)
    {
        sb.AppendLine($"    public int CompareTo({name} other) => Value.CompareTo(other.Value);");
        sb.AppendLine();
        // MA0097 requires comparison operators on types that implement IComparable<T>.
        sb.AppendLine($"    public static bool operator <({name} left, {name} right) => left.CompareTo(right) < 0;");
        sb.AppendLine($"    public static bool operator >({name} left, {name} right) => left.CompareTo(right) > 0;");
        sb.AppendLine($"    public static bool operator <=({name} left, {name} right) => left.CompareTo(right) <= 0;");
        sb.AppendLine($"    public static bool operator >=({name} left, {name} right) => left.CompareTo(right) >= 0;");
        sb.AppendLine();
    }

    private static void AppendJsonConverter(StringBuilder sb, string name)
    {
        sb.AppendLine($"    internal sealed class TypedIdJsonConverter : JsonConverter<{name}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public override {name} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            var s = reader.GetString();");
        sb.AppendLine("            return s is not null && TryParse(s, CultureInfo.InvariantCulture, out var id)");
        sb.AppendLine("                ? id");
        sb.AppendLine($"                : throw new JsonException($\"Invalid {name} value.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public override void Write(Utf8JsonWriter writer, {name} value, JsonSerializerOptions options)");
        sb.AppendLine("            => writer.WriteStringValue(value.ToString());");
        sb.AppendLine("    }");
    }
}
