using System;
using System.Text;
using ZeroAlloc.ValueObjects.Generator.Models;

namespace ZeroAlloc.ValueObjects.Generator.Writers;

internal static class TypedIdInt64Writer
{
    public static string Write(TypedIdModel model)
    {
        var sb = new StringBuilder();
        AppendHeader(sb, model);
        AppendTypeDeclaration(sb, model.Name);
        AppendValueAndCtor(sb, model.Name);
        AppendFactory(sb, model.Name, model.Strategy);
        AppendFormatting(sb);
        AppendParsing(sb, model.Name);
        AppendComparable(sb, model.Name);
        AppendJsonConverter(sb, model.Name);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb, TypedIdModel model)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using ZeroAlloc.ValueObjects;");
        sb.AppendLine();
        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }
    }

    private static void AppendTypeDeclaration(StringBuilder sb, string name)
    {
        sb.AppendLine($"[JsonConverter(typeof({name}.TypedIdJsonConverter))]");
        sb.AppendLine($"public readonly partial record struct {name} :");
        sb.AppendLine($"    IEquatable<{name}>,");
        sb.AppendLine($"    IComparable<{name}>,");
        sb.AppendLine($"    IParsable<{name}>,");
        sb.AppendLine($"    ISpanParsable<{name}>");
        sb.AppendLine("{");
    }

    private static void AppendValueAndCtor(StringBuilder sb, string name)
    {
        sb.AppendLine("    public long Value { get; }");
        sb.AppendLine();
        sb.AppendLine($"    public {name}(long value) => Value = value;");
        sb.AppendLine();
    }

    private static void AppendFactory(StringBuilder sb, string name, int strategy)
    {
        switch (strategy)
        {
            case 2: // Snowflake
                sb.AppendLine($"    public static {name} New()");
                sb.AppendLine("    {");
                sb.AppendLine("        int workerId = ResolveWorkerId();");
                sb.AppendLine($"        return new {name}(SnowflakeCore.Next(workerId));");
                sb.AppendLine("    }");
                sb.AppendLine();
                AppendResolveWorkerId(sb);
                break;
            case 3: // Sequential
                sb.AppendLine($"    public static {name} New() => new(SequentialCore.Next());");
                sb.AppendLine();
                break;
            default:
                throw new InvalidOperationException($"Unexpected Int64-backed strategy {strategy}");
        }
    }

    private static void AppendResolveWorkerId(StringBuilder sb)
    {
        sb.AppendLine("    private static int ResolveWorkerId()");
        sb.AppendLine("    {");
        sb.AppendLine("        var provider = TypedIdRuntime.SnowflakeProvider;");
        sb.AppendLine("        if (provider is not null) return provider.WorkerId;");
        sb.AppendLine();
        sb.AppendLine("        var raw = Environment.GetEnvironmentVariable(\"ZA_SNOWFLAKE_WORKER_ID\");");
        sb.AppendLine("        if (raw is not null && int.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out var fromEnv))");
        sb.AppendLine("            return fromEnv;");
        sb.AppendLine();
        sb.AppendLine("        throw new TypedIdException(");
        sb.AppendLine("            \"Snowflake worker id not configured. Call services.AddSnowflakeWorkerId(...) \" +");
        sb.AppendLine("            \"or set the ZA_SNOWFLAKE_WORKER_ID environment variable.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendFormatting(StringBuilder sb)
    {
        sb.AppendLine("    public override string ToString() => Value.ToString(CultureInfo.InvariantCulture);");
        sb.AppendLine();
    }

    private static void AppendParsing(StringBuilder sb, string name)
    {
        sb.AppendLine($"    public static {name} Parse(string s, IFormatProvider? provider = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (s is null) throw new ArgumentNullException(nameof(s));");
        sb.AppendLine("        if (long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))");
        sb.AppendLine($"            return new {name}(v);");
        sb.AppendLine($"        throw new FormatException($\"Value is not a valid {name}.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static bool TryParse(string? s, IFormatProvider? provider, out {name} result)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (s is not null && long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))");
        sb.AppendLine("        {");
        sb.AppendLine($"            result = new {name}(v);");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        result = default;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static {name} Parse(ReadOnlySpan<char> s, IFormatProvider? provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))");
        sb.AppendLine($"            return new {name}(v);");
        sb.AppendLine($"        throw new FormatException($\"Value is not a valid {name}.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out {name} result)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))");
        sb.AppendLine("        {");
        sb.AppendLine($"            result = new {name}(v);");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        result = default;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendComparable(StringBuilder sb, string name)
    {
        sb.AppendLine($"    public int CompareTo({name} other) => Value.CompareTo(other.Value);");
        sb.AppendLine();
        // MA0097 requires comparison operators on types that implement IComparable<T>.
        sb.AppendLine($"    public static bool operator <({name} left, {name} right) => left.CompareTo(right) < 0;");
        sb.AppendLine($"    public static bool operator >({name} left, {name} right) => left.CompareTo(right) > 0;");
        sb.AppendLine($"    public static bool operator <=({name} left, {name} right) => left.CompareTo(right) <= 0;");
        sb.AppendLine($"    public static bool operator >=({name} left, {name} right) => left.CompareTo(right) >= 0;");
        sb.AppendLine();
    }

    private static void AppendJsonConverter(StringBuilder sb, string name)
    {
        sb.AppendLine($"    internal sealed class TypedIdJsonConverter : JsonConverter<{name}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public override {name} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            var s = reader.GetString();");
        sb.AppendLine("            return s is not null && TryParse(s, CultureInfo.InvariantCulture, out var id)");
        sb.AppendLine("                ? id");
        sb.AppendLine($"                : throw new JsonException($\"Invalid {name} value.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public override void Write(Utf8JsonWriter writer, {name} value, JsonSerializerOptions options)");
        sb.AppendLine("            => writer.WriteStringValue(value.ToString());");
        sb.AppendLine("    }");
    }
}
