using System;
using System.Text;
using ZeroAlloc.ValueObjects.Generator.Models;

namespace ZeroAlloc.ValueObjects.Generator.Writers;

internal static class TypedIdInt64Writer
{
    public static string Write(TypedIdModel model)
    {
        var sb = new StringBuilder();
        // A keyword name is written as a verbatim identifier wherever it is used as a type.
        var name = TypeDeclarations.Identifier(model.Name);
        AppendHeader(sb, model);
        AppendTypeDeclaration(sb, name, model.Accessibility);
        AppendValueAndCtor(sb, name);
        AppendFactory(sb, name, model.Strategy);
        AppendFormatting(sb);
        AppendParsing(sb, name);
        AppendComparable(sb, name);
        AppendJsonConverter(sb, name);
        AppendZeroAllocSerializer(sb, name);
        sb.AppendLine("}");
        for (var i = 0; i < model.ContainingTypes.Count; i++) sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb, TypedIdModel model)
    {
        sb.AppendLine("// <auto-generated/>");
        // The <auto-generated> header suppresses analyzer diagnostics but not compiler ones,
        // so CS1591 still fires on every public member for consumers who enable
        // GenerateDocumentationFile. Suppress it here — file-scoped, so it can't leak into
        // the consumer's hand-written code.
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using ZeroAlloc.ValueObjects;");
        sb.AppendLine();
        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        // A nested struct is emitted inside partial declarations of its containing types.
        foreach (var containing in model.ContainingTypes)
        {
            sb.AppendLine(containing);
            sb.AppendLine("{");
        }
    }

    // The declared accessibility is repeated, so an internal or nested private struct gets no
    // conflicting modifier (CS0262); a file-local struct is never generated.
    private static void AppendTypeDeclaration(StringBuilder sb, string name, string accessibility)
    {
        sb.AppendLine($"[JsonConverter(typeof({name}.TypedIdJsonConverter))]");
        sb.AppendLine($"{accessibility} readonly partial record struct {name} :");
        sb.AppendLine($"    IEquatable<{name}>,");
        sb.AppendLine($"    IComparable<{name}>,");
        sb.AppendLine($"    IParsable<{name}>,");
        sb.AppendLine($"    ISpanParsable<{name}>");
        sb.AppendLine("{");
    }

    private static void AppendValueAndCtor(StringBuilder sb, string name)
    {
        sb.AppendLine("    /// <summary>The underlying 64-bit value this identifier wraps.</summary>");
        sb.AppendLine("    public long Value { get; }");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Wraps an existing 64-bit value as a <c>{name}</c>. No validation is performed.</summary>");
        sb.AppendLine("    /// <param name=\"value\">The value to wrap.</param>");
        sb.AppendLine($"    public {name}(long value) => Value = value;");
        sb.AppendLine();
    }

    private static void AppendFactory(StringBuilder sb, string name, int strategy)
    {
        switch (strategy)
        {
            case 2: // Snowflake
                sb.AppendLine("    /// <summary>Creates a new Snowflake identifier: time-ordered and monotonically increasing per worker.</summary>");
                sb.AppendLine("    /// <remarks>");
                sb.AppendLine("    /// Requires a worker id, resolved from the configured Snowflake provider (services.AddSnowflakeWorkerId)");
                sb.AppendLine("    /// or the ZA_SNOWFLAKE_WORKER_ID environment variable. Throws TypedIdException if neither is set.");
                sb.AppendLine("    /// </remarks>");
                sb.AppendLine("    /// <returns>A new unique identifier.</returns>");
                sb.AppendLine($"    public static {name} New()");
                sb.AppendLine("    {");
                sb.AppendLine("        int workerId = ResolveWorkerId();");
                sb.AppendLine($"        return new {name}(SnowflakeCore.Next(workerId));");
                sb.AppendLine("    }");
                sb.AppendLine();
                AppendResolveWorkerId(sb);
                break;
            case 3: // Sequential
                sb.AppendLine("    /// <summary>Creates a new sequential identifier, monotonically increasing within this process.</summary>");
                sb.AppendLine("    /// <returns>A new identifier, unique within this process.</returns>");
                sb.AppendLine($"    public static {name} New() => new(SequentialCore.Next());");
                sb.AppendLine();
                break;
            default:
                throw new InvalidOperationException($"Unexpected Int64-backed strategy {strategy}");
        }
    }

    private static void AppendResolveWorkerId(StringBuilder sb)
    {
        sb.AppendLine("    private static int ResolveWorkerId()");
        sb.AppendLine("    {");
        sb.AppendLine("        var provider = TypedIdRuntime.SnowflakeProvider;");
        sb.AppendLine("        if (provider is not null) return provider.WorkerId;");
        sb.AppendLine();
        sb.AppendLine("        var raw = Environment.GetEnvironmentVariable(\"ZA_SNOWFLAKE_WORKER_ID\");");
        sb.AppendLine("        if (raw is not null && int.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out var fromEnv))");
        sb.AppendLine("            return fromEnv;");
        sb.AppendLine();
        sb.AppendLine("        throw new TypedIdException(");
        sb.AppendLine("            \"Snowflake worker id not configured. Call services.AddSnowflakeWorkerId(...) \" +");
        sb.AppendLine("            \"or set the ZA_SNOWFLAKE_WORKER_ID environment variable.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendFormatting(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Returns the invariant decimal form of the underlying value. This is the form accepted by Parse and TryParse.</summary>");
        sb.AppendLine("    public override string ToString() => Value.ToString(CultureInfo.InvariantCulture);");
        sb.AppendLine();
    }

    // Split string/span overloads into separate methods to stay under MA0051's statement limit.
    private static void AppendParsing(StringBuilder sb, string name)
    {
        AppendParseWithoutProvider(sb, name);
        AppendStringParsing(sb, name);
        AppendSpanParsing(sb, name);
    }

    // A separate one-argument overload rather than an optional provider: the span overload has the
    // same parameter count, so an optional parameter here trips RS0027 in every consumer that tracks
    // its public API. Callers compiled against the old optional form keep working, since the
    // two-argument signature is unchanged.
    private static void AppendParseWithoutProvider(StringBuilder sb, string name)
    {
        TypedIdDocs.AppendParseWithoutProviderDoc(sb, name);
        sb.AppendLine($"    public static {name} Parse(string s) => Parse(s, null);");
        sb.AppendLine();
    }

    private static void AppendStringParsing(StringBuilder sb, string name)
    {
        TypedIdDocs.AppendParseDoc(sb, name, span: false, nullThrows: true);
        sb.AppendLine($"    public static {name} Parse(string s, IFormatProvider? provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (s is null) throw new ArgumentNullException(nameof(s));");
        sb.AppendLine("        if (long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))");
        sb.AppendLine($"            return new {name}(v);");
        sb.AppendLine($"        throw new FormatException($\"Value is not a valid {name}.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        TypedIdDocs.AppendTryParseDoc(sb, name, span: false);
        sb.AppendLine($"    public static bool TryParse(string? s, IFormatProvider? provider, out {name} result)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (s is not null && long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))");
        sb.AppendLine("        {");
        sb.AppendLine($"            result = new {name}(v);");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        result = default;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendSpanParsing(StringBuilder sb, string name)
    {
        TypedIdDocs.AppendParseDoc(sb, name, span: true, nullThrows: false);
        sb.AppendLine($"    public static {name} Parse(ReadOnlySpan<char> s, IFormatProvider? provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))");
        sb.AppendLine($"            return new {name}(v);");
        sb.AppendLine($"        throw new FormatException($\"Value is not a valid {name}.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        TypedIdDocs.AppendTryParseDoc(sb, name, span: true);
        sb.AppendLine($"    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out {name} result)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))");
        sb.AppendLine("        {");
        sb.AppendLine($"            result = new {name}(v);");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        result = default;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendComparable(StringBuilder sb, string name)
    {
        TypedIdDocs.AppendCompareToDoc(sb, name);
        sb.AppendLine($"    public int CompareTo({name} other) => Value.CompareTo(other.Value);");
        sb.AppendLine();
        // MA0097 requires comparison operators on types that implement IComparable<T>.
        TypedIdDocs.AppendComparisonOperatorDoc(sb, name, "less than");
        sb.AppendLine($"    public static bool operator <({name} left, {name} right) => left.CompareTo(right) < 0;");
        TypedIdDocs.AppendComparisonOperatorDoc(sb, name, "greater than");
        sb.AppendLine($"    public static bool operator >({name} left, {name} right) => left.CompareTo(right) > 0;");
        TypedIdDocs.AppendComparisonOperatorDoc(sb, name, "less than or equal to");
        sb.AppendLine($"    public static bool operator <=({name} left, {name} right) => left.CompareTo(right) <= 0;");
        TypedIdDocs.AppendComparisonOperatorDoc(sb, name, "greater than or equal to");
        sb.AppendLine($"    public static bool operator >=({name} left, {name} right) => left.CompareTo(right) >= 0;");
        sb.AppendLine();
    }

    private static void AppendJsonConverter(StringBuilder sb, string name)
    {
        TypedIdDocs.AppendJsonConverterDoc(sb, name);
        sb.AppendLine($"    public sealed class TypedIdJsonConverter : JsonConverter<{name}>");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine($"        public override {name} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            var s = reader.GetString();");
        sb.AppendLine("            return s is not null && TryParse(s, CultureInfo.InvariantCulture, out var id)");
        sb.AppendLine("                ? id");
        sb.AppendLine($"                : throw new JsonException($\"Invalid {name} value.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine($"        public override void Write(Utf8JsonWriter writer, {name} value, JsonSerializerOptions options)");
        sb.AppendLine("            => writer.WriteStringValue(value.ToString());");
        sb.AppendLine("    }");
    }

    // Emits a nested ISerializer<TypedId> implementation alongside the existing
    // JsonConverter<T>. Closes ValueObjects#25 — additive integration with
    // ZeroAlloc.Serialisation. Guarded by the modern-TFM symbol because the
    // package reference to ZeroAlloc.Serialisation is conditional on the same
    // TFM in ZeroAlloc.ValueObjects.csproj. The byte form is little-endian
    // Int64 via BinaryPrimitives — zero-alloc round-trip in both directions.
    private static void AppendZeroAllocSerializer(StringBuilder sb, string name)
    {
        sb.AppendLine();
        sb.AppendLine("#if NETSTANDARD2_1_OR_GREATER || NET");
        sb.AppendLine($"    internal sealed class TypedIdSerializer : global::ZeroAlloc.Serialisation.ISerializer<{name}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public void Serialize(global::System.Buffers.IBufferWriter<byte> writer, {name} value)");
        sb.AppendLine("        {");
        sb.AppendLine("            var span = writer.GetSpan(8);");
        sb.AppendLine("            global::System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(span, value.Value);");
        sb.AppendLine("            writer.Advance(8);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {name} Deserialize(global::System.ReadOnlySpan<byte> buffer)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (buffer.Length < 8)");
        sb.AppendLine($"                throw new global::System.ArgumentException($\"Buffer too small to deserialize {name}; need 8 bytes, got {{buffer.Length}}.\", nameof(buffer));");
        sb.AppendLine($"            return new {name}(global::System.Buffers.Binary.BinaryPrimitives.ReadInt64LittleEndian(buffer.Slice(0, 8)));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("#endif");
    }
}
