using System;
using System.Linq.Expressions;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ZeroAlloc.ValueObjects.EfCore;

/// <summary>
/// EF Core value converter for a TypedId struct. Converts between the TypedId's
/// <c>Value</c> property and its backing type (<see cref="Guid"/> or <see cref="long"/>).
/// </summary>
/// <typeparam name="TId">The TypedId struct (must expose <c>Value</c> of type <typeparamref name="TBacking"/>).</typeparam>
/// <typeparam name="TBacking">The backing primitive: <see cref="Guid"/> or <see cref="long"/>.</typeparam>
public sealed class TypedIdValueConverter<TId, TBacking> : ValueConverter<TId, TBacking>
    where TId : struct
{
    public TypedIdValueConverter()
        : base(BuildToProvider(), BuildFromProvider())
    {
    }

    private static Expression<Func<TId, TBacking>> BuildToProvider()
    {
        // (id) => id.Value
        var param = Expression.Parameter(typeof(TId), "id");
        var valueProp = typeof(TId).GetProperty("Value", BindingFlags.Instance | BindingFlags.Public)
            ?? throw new InvalidOperationException(
                $"TypedId struct '{typeof(TId).FullName}' is missing public 'Value' property. " +
                "Was it generated by the TypedId source generator?");
        if (valueProp.PropertyType != typeof(TBacking))
            throw new InvalidOperationException(
                $"TypedId struct '{typeof(TId).FullName}' has Value of type '{valueProp.PropertyType.Name}' " +
                $"but the converter was constructed with backing '{typeof(TBacking).Name}'.");
        var access = Expression.Property(param, valueProp);
        return Expression.Lambda<Func<TId, TBacking>>(access, param);
    }

    private static Expression<Func<TBacking, TId>> BuildFromProvider()
    {
        // (v) => new TId(v)
        var param = Expression.Parameter(typeof(TBacking), "v");
        var ctor = typeof(TId).GetConstructor(new[] { typeof(TBacking) })
            ?? throw new InvalidOperationException(
                $"TypedId struct '{typeof(TId).FullName}' is missing single-arg constructor taking '{typeof(TBacking).Name}'. " +
                "Was it generated by the TypedId source generator?");
        var ctorCall = Expression.New(ctor, param);
        return Expression.Lambda<Func<TBacking, TId>>(ctorCall, param);
    }
}
