//HintName: Wide.g.cs
// <auto-generated />
#nullable enable

sealed partial class Wide : System.IEquatable<Wide>
{
    public override bool Equals(object? obj) =>
        obj is Wide other && Equals(other);

    public bool Equals(Wide other) =>
        A == other.A &&
        B == other.B &&
        C == other.C &&
        D == other.D &&
        E == other.E &&
        F == other.F &&
        G == other.G &&
        H == other.H &&
        I == other.I;

    public override int GetHashCode()
    {
        var hc = new System.HashCode();
        hc.Add(A);
        hc.Add(B);
        hc.Add(C);
        hc.Add(D);
        hc.Add(E);
        hc.Add(F);
        hc.Add(G);
        hc.Add(H);
        hc.Add(I);
        return hc.ToHashCode();
    }

    public static bool operator ==(Wide left, Wide right) => left.Equals(right);
    public static bool operator !=(Wide left, Wide right) => !left.Equals(right);

    public override string ToString() => $"Wide {{ A = {A}, B = {B}, C = {C}, D = {D}, E = {E}, F = {F}, G = {G}, H = {H}, I = {I} }}";
}
