//HintName: Product.g.cs
// <auto-generated />
#nullable enable

sealed partial class Product : System.IEquatable<Product>
{
    public override bool Equals(object? obj) =>
        obj is Product other && Equals(other);

    public bool Equals(Product other) =>
        Name == other.Name;

    public override int GetHashCode()
    {
        return System.HashCode.Combine(Name);
    }

    public static bool operator ==(Product left, Product right) => left.Equals(right);
    public static bool operator !=(Product left, Product right) => !left.Equals(right);

    public override string ToString() => $"Product { Name = {Name} }";
}
