//HintName: Address.g.cs
// <auto-generated />
#pragma warning disable CS1591
#nullable enable

sealed partial class Address : System.IEquatable<Address>
{
    /// <inheritdoc/>
    public override bool Equals(object? obj) =>
        obj is Address other && Equals(other);

    /// <inheritdoc/>
    public bool Equals(Address? other) =>
        other is not null &&
        Street == other.Street &&
        City == other.City;

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return System.HashCode.Combine(Street, City);
    }

    /// <summary>Determines whether two <c>Address</c> values are equal by comparing their equality members.</summary>
    /// <param name="left">The left operand.</param>
    /// <param name="right">The right operand.</param>
    /// <returns><see langword="true"/> if the values are equal; otherwise <see langword="false"/>.</returns>
    public static bool operator ==(Address? left, Address? right) => left is null ? right is null : left.Equals(right);
    /// <summary>Determines whether two <c>Address</c> values are not equal by comparing their equality members.</summary>
    /// <param name="left">The left operand.</param>
    /// <param name="right">The right operand.</param>
    /// <returns><see langword="true"/> if the values are not equal; otherwise <see langword="false"/>.</returns>
    public static bool operator !=(Address? left, Address? right) => !(left == right);

    /// <summary>Returns a string listing each equality member of this <c>Address</c> as Name = value.</summary>
    public override string ToString() => $"Address {{ Street = {Street}, City = {City} }}";
}
