//HintName: Address.g.cs
// <auto-generated />
#nullable enable

sealed partial class Address : System.IEquatable<Address>
{
    public override bool Equals(object? obj) =>
        obj is Address other && Equals(other);

    public bool Equals(Address other) =>
        Street == other.Street &&
        City == other.City;

    public override int GetHashCode()
    {
        return System.HashCode.Combine(Street, City);
    }

    public static bool operator ==(Address left, Address right) => left.Equals(right);
    public static bool operator !=(Address left, Address right) => !left.Equals(right);

    public override string ToString() => $"Address {{ Street = {Street}, City = {City} }}";
}
