//HintName: Money.g.cs
// <auto-generated />
#nullable enable

sealed partial class Money : System.IEquatable<Money>
{
    public override bool Equals(object? obj) =>
        obj is Money other && Equals(other);

    public bool Equals(Money? other) =>
        other is not null &&
        Amount == other.Amount &&
        Currency == other.Currency;

    public override int GetHashCode()
    {
        return System.HashCode.Combine(Amount, Currency);
    }

    public static bool operator ==(Money? left, Money? right) => left is null ? right is null : left.Equals(right);
    public static bool operator !=(Money? left, Money? right) => !(left == right);

    public override string ToString() => $"Money {{ Amount = {Amount}, Currency = {Currency} }}";
}
