//HintName: Amount.g.cs
// <auto-generated />
#nullable enable

readonly partial struct Amount : System.IEquatable<Amount>
{
    public override bool Equals(object? obj) =>
        obj is Amount other && Equals(other);

    public bool Equals(Amount other) =>
        Value == other.Value;

    public override int GetHashCode()
    {
        return System.HashCode.Combine(Value);
    }

    public static bool operator ==(Amount left, Amount right) => left.Equals(right);
    public static bool operator !=(Amount left, Amount right) => !left.Equals(right);

    public override string ToString() => $"Amount {{ Value = {Value} }}";
}
