//HintName: Wide.g.cs
// <auto-generated />
#pragma warning disable CS1591
#nullable enable

sealed partial class Wide : System.IEquatable<Wide>
{
    /// <inheritdoc/>
    public override bool Equals(object? obj) =>
        obj is Wide other && Equals(other);

    /// <inheritdoc/>
    public bool Equals(Wide? other) =>
        other is not null &&
        A == other.A &&
        B == other.B &&
        C == other.C &&
        D == other.D &&
        E == other.E &&
        F == other.F &&
        G == other.G &&
        H == other.H &&
        I == other.I;

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        var hc = new System.HashCode();
        hc.Add(A);
        hc.Add(B);
        hc.Add(C);
        hc.Add(D);
        hc.Add(E);
        hc.Add(F);
        hc.Add(G);
        hc.Add(H);
        hc.Add(I);
        return hc.ToHashCode();
    }

    /// <summary>Determines whether two <c>Wide</c> values are equal by comparing their equality members.</summary>
    /// <param name="left">The left operand.</param>
    /// <param name="right">The right operand.</param>
    /// <returns><see langword="true"/> if the values are equal; otherwise <see langword="false"/>.</returns>
    public static bool operator ==(Wide? left, Wide? right) => left is null ? right is null : left.Equals(right);
    /// <summary>Determines whether two <c>Wide</c> values are not equal by comparing their equality members.</summary>
    /// <param name="left">The left operand.</param>
    /// <param name="right">The right operand.</param>
    /// <returns><see langword="true"/> if the values are not equal; otherwise <see langword="false"/>.</returns>
    public static bool operator !=(Wide? left, Wide? right) => !(left == right);

    /// <summary>Returns a string listing each equality member of this <c>Wide</c> as Name = value.</summary>
    public override string ToString() => $"Wide {{ A = {A}, B = {B}, C = {C}, D = {D}, E = {E}, F = {F}, G = {G}, H = {H}, I = {I} }}";
}
