//HintName: App.Orders+Keys+Id.TypedId.g.cs
// <auto-generated/>
#pragma warning disable CS1591
#nullable enable

using System;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;
using ZeroAlloc.ValueObjects;

namespace App;

partial record struct Orders
{
partial class Keys
{
[JsonConverter(typeof(Id.TypedIdJsonConverter))]
private readonly partial record struct Id :
    IEquatable<Id>,
    IComparable<Id>,
    IParsable<Id>,
    ISpanParsable<Id>
{
    /// <summary>The underlying 64-bit value this identifier wraps.</summary>
    public long Value { get; }

    /// <summary>Wraps an existing 64-bit value as a <c>Id</c>. No validation is performed.</summary>
    /// <param name="value">The value to wrap.</param>
    public Id(long value) => Value = value;

    /// <summary>Creates a new sequential identifier, monotonically increasing within this process.</summary>
    /// <returns>A new identifier, unique within this process.</returns>
    public static Id New() => new(SequentialCore.Next());

    /// <summary>Returns the invariant decimal form of the underlying value. This is the form accepted by Parse and TryParse.</summary>
    public override string ToString() => Value.ToString(CultureInfo.InvariantCulture);

    /// <summary>Parses a string into a <c>Id</c>, accepting the same form produced by ToString.</summary>
    /// <param name="s">The string to parse.</param>
    /// <returns>The parsed <c>Id</c>.</returns>
    /// <exception cref="System.ArgumentNullException"><paramref name="s"/> is null.</exception>
    /// <exception cref="System.FormatException"><paramref name="s"/> is not a valid <c>Id</c>.</exception>
    public static Id Parse(string s) => Parse(s, null);

    /// <summary>Parses a string into a <c>Id</c>, accepting the same form produced by ToString.</summary>
    /// <param name="s">The string to parse.</param>
    /// <param name="provider">Ignored; the format is culture-invariant. Present to satisfy the parsing interfaces.</param>
    /// <returns>The parsed <c>Id</c>.</returns>
    /// <exception cref="System.ArgumentNullException"><paramref name="s"/> is null.</exception>
    /// <exception cref="System.FormatException"><paramref name="s"/> is not a valid <c>Id</c>.</exception>
    public static Id Parse(string s, IFormatProvider? provider)
    {
        if (s is null) throw new ArgumentNullException(nameof(s));
        if (long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))
            return new Id(v);
        throw new FormatException($"Value is not a valid Id.");
    }

    /// <summary>Attempts to parse a string into a <c>Id</c>. Returns false for a null input rather than throwing.</summary>
    /// <param name="s">The string to parse.</param>
    /// <param name="provider">Ignored; the format is culture-invariant. Present to satisfy the parsing interfaces.</param>
    /// <param name="result">The parsed <c>Id</c> on success; otherwise the default value.</param>
    /// <returns><see langword="true"/> if parsing succeeded; otherwise <see langword="false"/>.</returns>
    public static bool TryParse(string? s, IFormatProvider? provider, out Id result)
    {
        if (s is not null && long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))
        {
            result = new Id(v);
            return true;
        }
        result = default;
        return false;
    }

    /// <summary>Parses a character span into a <c>Id</c>, accepting the same form produced by ToString.</summary>
    /// <param name="s">The character span to parse.</param>
    /// <param name="provider">Ignored; the format is culture-invariant. Present to satisfy the parsing interfaces.</param>
    /// <returns>The parsed <c>Id</c>.</returns>
    /// <exception cref="System.FormatException"><paramref name="s"/> is not a valid <c>Id</c>.</exception>
    public static Id Parse(ReadOnlySpan<char> s, IFormatProvider? provider)
    {
        if (long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))
            return new Id(v);
        throw new FormatException($"Value is not a valid Id.");
    }

    /// <summary>Attempts to parse a character span into a <c>Id</c>.</summary>
    /// <param name="s">The character span to parse.</param>
    /// <param name="provider">Ignored; the format is culture-invariant. Present to satisfy the parsing interfaces.</param>
    /// <param name="result">The parsed <c>Id</c> on success; otherwise the default value.</param>
    /// <returns><see langword="true"/> if parsing succeeded; otherwise <see langword="false"/>.</returns>
    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out Id result)
    {
        if (long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v))
        {
            result = new Id(v);
            return true;
        }
        result = default;
        return false;
    }

    /// <summary>Compares this identifier with another by their underlying values.</summary>
    /// <param name="other">The <c>Id</c> to compare against.</param>
    /// <returns>A negative value if this instance precedes <paramref name="other"/>, zero if they are equal, otherwise a positive value.</returns>
    public int CompareTo(Id other) => Value.CompareTo(other.Value);

    /// <summary>Determines whether one <c>Id</c> is less than another, comparing their underlying values.</summary>
    /// <param name="left">The left operand.</param>
    /// <param name="right">The right operand.</param>
    /// <returns><see langword="true"/> if the left operand is less than the right; otherwise <see langword="false"/>.</returns>
    public static bool operator <(Id left, Id right) => left.CompareTo(right) < 0;
    /// <summary>Determines whether one <c>Id</c> is greater than another, comparing their underlying values.</summary>
    /// <param name="left">The left operand.</param>
    /// <param name="right">The right operand.</param>
    /// <returns><see langword="true"/> if the left operand is greater than the right; otherwise <see langword="false"/>.</returns>
    public static bool operator >(Id left, Id right) => left.CompareTo(right) > 0;
    /// <summary>Determines whether one <c>Id</c> is less than or equal to another, comparing their underlying values.</summary>
    /// <param name="left">The left operand.</param>
    /// <param name="right">The right operand.</param>
    /// <returns><see langword="true"/> if the left operand is less than or equal to the right; otherwise <see langword="false"/>.</returns>
    public static bool operator <=(Id left, Id right) => left.CompareTo(right) <= 0;
    /// <summary>Determines whether one <c>Id</c> is greater than or equal to another, comparing their underlying values.</summary>
    /// <param name="left">The left operand.</param>
    /// <param name="right">The right operand.</param>
    /// <returns><see langword="true"/> if the left operand is greater than or equal to the right; otherwise <see langword="false"/>.</returns>
    public static bool operator >=(Id left, Id right) => left.CompareTo(right) >= 0;

    /// <summary>Converts a <c>Id</c> to and from its JSON string form.</summary>
    /// <remarks>
    /// Applied to <c>Id</c> via JsonConverterAttribute, so reflection-based serialization picks it up
    /// automatically. Source-generated serialization requires registering it explicitly.
    /// </remarks>
    public sealed class TypedIdJsonConverter : JsonConverter<Id>
    {
        /// <inheritdoc/>
        public override Id Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var s = reader.GetString();
            return s is not null && TryParse(s, CultureInfo.InvariantCulture, out var id)
                ? id
                : throw new JsonException($"Invalid Id value.");
        }

        /// <inheritdoc/>
        public override void Write(Utf8JsonWriter writer, Id value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString());
    }

#if NETSTANDARD2_1_OR_GREATER || NET
    internal sealed class TypedIdSerializer : global::ZeroAlloc.Serialisation.ISerializer<Id>
    {
        public void Serialize(global::System.Buffers.IBufferWriter<byte> writer, Id value)
        {
            var span = writer.GetSpan(8);
            global::System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(span, value.Value);
            writer.Advance(8);
        }

        public Id Deserialize(global::System.ReadOnlySpan<byte> buffer)
        {
            if (buffer.Length < 8)
                throw new global::System.ArgumentException($"Buffer too small to deserialize Id; need 8 bytes, got {buffer.Length}.", nameof(buffer));
            return new Id(global::System.Buffers.Binary.BinaryPrimitives.ReadInt64LittleEndian(buffer.Slice(0, 8)));
        }
    }
#endif
}
}
}
