//HintName: App.Holder`1+Values`1+Money`1.g.cs
// <auto-generated />
#pragma warning disable CS1591
#nullable enable

namespace App;

partial struct Holder<T>
{
partial class Values<U>
{
sealed partial class Money<V> : System.IEquatable<Money<V>>
{
    /// <inheritdoc/>
    public override bool Equals(object? obj) =>
        obj is Money<V> other && Equals(other);

    /// <inheritdoc/>
    public bool Equals(Money<V>? other) =>
        other is not null &&
        global::System.Collections.Generic.EqualityComparer<V>.Default.Equals(Amount, other.Amount) &&
        Currency == other.Currency;

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return System.HashCode.Combine(Amount, Currency);
    }

    /// <summary>Determines whether two <c>Money</c> values are equal by comparing their equality members.</summary>
    /// <param name="left">The left operand.</param>
    /// <param name="right">The right operand.</param>
    /// <returns><see langword="true"/> if the values are equal; otherwise <see langword="false"/>.</returns>
    public static bool operator ==(Money<V>? left, Money<V>? right) => left is null ? right is null : left.Equals(right);
    /// <summary>Determines whether two <c>Money</c> values are not equal by comparing their equality members.</summary>
    /// <param name="left">The left operand.</param>
    /// <param name="right">The right operand.</param>
    /// <returns><see langword="true"/> if the values are not equal; otherwise <see langword="false"/>.</returns>
    public static bool operator !=(Money<V>? left, Money<V>? right) => !(left == right);

    /// <summary>Returns a string listing each equality member of this <c>Money</c> as Name = value.</summary>
    public override string ToString() => $"Money {{ Amount = {Amount}, Currency = {Currency} }}";
}
}
}
